package(default_visibility = ['PUBLIC'])

remote_file(
   name = 'dotnet',
   url = 'https://raw.githubusercontent.com/Ordsall/dotnet-pleasing/master/dotnet.build_defs',
   visibility = ['PUBLIC'],
)
